"""
Per-slug metadata for gallery entries. Used by apply_metadata.py.
Slug = stem.lower().replace(' ', '-').replace('_', '-') (same as watermark.py).
"""

# Build MAPPING: slug -> {species, title, location?, categories, tags, caption?, description?}
# DSC ranges: (lo, hi, meta) or explicit list of numbers; then slug = f"dsc-{n:04d}" or "dsc-xxxx" for variants like (2), ~2

def _meta(species, title, categories=None, tags=None, location="India", caption="", description=""):
    return {
        "species": species,
        "title": title,
        "location": location,
        "categories": categories or ["wildlife"],
        "tags": tags or [],
        "caption": caption or f"{species.split('(')[0].strip()} in urban India.",
        "description": description or "",
    }


# Shared meta dicts
B = ["birds"]
BW = ["birds", "waterbirds"]
M = ["mammals"]
R = ["birds", "raptors"]
INV = ["invertebrates", "macro"]
REP = ["reptiles"]
AMPH = ["amphibians"]
NATURE = ["nature"]

MAPPING = {}

# DSC number ranges and single numbers -> meta. (inclusive lo, hi) or list of numbers
def _dsc(num):
    return f"dsc-{num:04d}"

def _add_dsc(nums, meta):
    if isinstance(nums, range):
        nums = list(nums)
    elif isinstance(nums, tuple) and len(nums) == 2:
        nums = list(range(nums[0], nums[1] + 1))
    for n in nums:
        MAPPING[_dsc(n)] = meta

# --- From conversation summary: manual identifications ---
_add_dsc([22], _meta("Domestic Chicken (Gallus gallus domesticus)", "Hen with Chicks", B, ["chicken", "domestic", "backyard"]))
_add_dsc([26, 27, 31, 32, 83], _meta("Indian Spot-billed Duck (Anas poecilorhyncha)", "Spot-billed Ducks", BW, ["duck", "spot-billed", "waterfowl"]))
_add_dsc(range(213, 216), _meta("Indian Spot-billed Duck (Anas poecilorhyncha)", "Spot-billed Ducks on Water", BW, ["duck", "spot-billed"]))
_add_dsc([33, 34, 35, 36, 37], _meta("White-throated Kingfisher (Halcyon smyrnensis)", "White-throated Kingfisher", B, ["kingfisher", "halcyon"]))
_add_dsc([28, 29, 30], _meta("White-throated Kingfisher (Halcyon smyrnensis)", "White-throated Kingfisher", B, ["kingfisher"]))
_add_dsc([39], _meta("White-breasted Waterhen (Amaurornis phoenicurus)", "White-breasted Waterhen", BW, ["waterhen", "rail"]))
_add_dsc([58], _meta("Indian Roller (Coracias benghalensis)", "Indian Roller", B, ["roller", "coracias"]))
_add_dsc([126, 347, 350, 1264, 3695, 3709, 3711, 3712, 3714, 4009, 4030, 4091, 4181, 4253, 4293, 4446, 4467, 4474, 4505, 4541, 4630, 4717, 4799, 4877, 5640], _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater", B, ["bee-eater", "merops"]))  # 4446 (2), 4717 (2) added below
_add_dsc([152, 216, 217, 221], _meta("Little Cormorant (Microcarbo niger)", "Little Cormorant", BW, ["cormorant", "waterbird"]))
_add_dsc([167, 169, 172, 312, 313, 318, 362, 1572, 8396, 9346, 9441], _meta("Common Kingfisher (Alcedo atthis)", "Common Kingfisher", BW, ["kingfisher", "alcedo"]))
_add_dsc([180, 184, 3772, 3773, 9513], _meta("Indian Grey Hornbill (Ocyceros birostris)", "Indian Grey Hornbill", B, ["hornbill", "ocyceros"]))
_add_dsc(range(218, 232), _meta("Grey Heron (Ardea cinerea)", "Grey Heron", BW, ["heron", "ardeidae"]))
_add_dsc([218, 219, 222, 223, 224, 226, 227, 228, 230, 231, 280, 330, 341, 443, 8621], _meta("Grey Heron (Ardea cinerea)", "Grey Heron", BW, ["heron"]))
_add_dsc([229, 463, 4508, 4509, 4632, 4669, 4671, 4933, 4935, 5201, 5202], _meta("Indian Pariah Dog (Canis lupus familiaris)", "Indian Street Dog", M, ["dog", "pariah", "street dog"]))
_add_dsc([234, 1659, 3151], _meta("House Sparrow (Passer domesticus)", "House Sparrow", B, ["sparrow", "passer"]))
_add_dsc([237, 239, 240, 241, 242, 243, 251, 255, 365, 431, 437, 447, 471, 474, 475, 2405, 4198], _meta("Black Kite (Milvus migrans)", "Black Kite", R, ["kite", "milvus", "raptor"]))
_add_dsc(range(256, 276), _meta("Indian Spectacled Cobra (Naja naja)", "Indian Cobra", REP, ["cobra", "snake", "naja"]))
_add_dsc([278, 279], _meta("Indian Spectacled Cobra (Naja naja)", "Indian Cobra", REP, ["cobra"]))
_add_dsc([281, 282, 283, 284, 336, 337, 343], _meta("Black-crowned Night Heron (Nycticorax nycticorax)", "Black-crowned Night Heron", BW, ["night heron", "nycticorax"]))
_add_dsc(range(286, 289), _meta("Indian Pond Heron (Ardeola grayii)", "Indian Pond Heron", BW, ["pond heron", "ardeola"]))
_add_dsc([325], _meta("Indian Pond Heron (Ardeola grayii)", "Indian Pond Heron", BW, ["pond heron"]))
_add_dsc([291, 3176, 3344, 3346, 3353, 4642, 7905], _meta("Oriental Garden Lizard (Calotes versicolor)", "Oriental Garden Lizard", REP, ["calotes", "lizard", "garden"]))
_add_dsc([300, 303, 304, 4835], _meta("White-browed Wagtail (Motacilla maderaspatensis)", "White-browed Wagtail", B, ["wagtail", "motacilla"]))
_add_dsc([326, 353, 4718, 4825], _meta("Common Coot (Fulica atra)", "Common Coot", BW, ["coot", "fulica"]))
_add_dsc([357, 3181, 3768, 8999, 9000, 9001], _meta("Indian Robin (Copsychus fulicatus)", "Indian Robin", B, ["indian robin", "copsychus"]))
_add_dsc([421], _meta("Moon (Lunar)", "Full Moon", ["nature", "astro"], ["moon", "astrophotography"]))
_add_dsc([435, 1601, 1602, 7641, 9939], _meta("Little Egret (Egretta garzetta)", "Little Egret", BW, ["egret", "egretta"]))
_add_dsc([440, 1278, 5621], _meta("Barn Swallow (Hirundo rustica)", "Barn Swallow", B, ["swallow", "hirundo"]))
_add_dsc([452, 455], _meta("Purple Heron (Ardea purpurea)", "Purple Heron", BW, ["heron", "purple heron"]))
_add_dsc([460, 1584, 1604, 4759, 1281], _meta("Little Cormorant (Microcarbo niger)", "Little Cormorant", BW, ["cormorant"]))
_add_dsc([464], _meta("Airplane", "Airplane with contrail", ["nature"], ["airplane", "contrail"]))
_add_dsc([478, 1669, 3698], _meta("Red-vented Bulbul (Pycnonotus cafer)", "Red-vented Bulbul", B, ["bulbul", "pycnonotus"]))
_add_dsc([501, 1610, 1612, 1644, 1646, 1657, 1660, 3887, 3907, 3914, 3952, 3974, 3994, 6075], _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet", "psittacula"]))
_add_dsc([556], _meta("Skink (Eutropis sp.)", "Indian Skink", REP, ["skink", "lizard"]))
_add_dsc([1145, 1149, 1153, 1162, 1165, 1199, 1227, 1246, 8893], _meta("Asian Openbill Stork (Anastomus oscitans)", "Asian Openbill", BW, ["stork", "openbill"]))
_add_dsc([1156, 1157, 1158, 1232, 5724, 5727], _meta("Painted Stork (Mycteria leucocephala)", "Painted Stork", BW, ["stork", "painted stork"]))
_add_dsc([1250, 8897], _meta("Black Drongo (Dicrurus macrocercus)", "Black Drongo", B, ["drongo", "dicrurus"]))
_add_dsc([1655, 3009, 3547, 5245, 5247, 8965, 8970], _meta("Indian Palm Squirrel (Funambulus palmarum)", "Indian Palm Squirrel", M, ["squirrel", "palm squirrel"]))
_add_dsc([1673], _meta("Grey Heron (Ardea cinerea)", "Juvenile Grey Heron", BW, ["heron", "juvenile"]))
_add_dsc([2643], _meta("Cabbage White butterfly larva (Pieris sp.)", "Butterfly Caterpillar", INV, ["caterpillar", "butterfly"]))
_add_dsc([3066], _meta("Rock Pigeon (Columba livia)", "Rock Pigeon", B, ["pigeon", "columba"]))
_add_dsc([3318], _meta("Asian Pied Starling (Gracupica contra)", "Asian Pied Starling", B, ["starling", "myna"]))
_add_dsc([3357, 3358], _meta("Common Myna (Acridotheres tristis)", "Common Myna", B, ["myna", "acridotheres"]))
_add_dsc([3385], _meta("Rhesus Macaque (Macaca mulatta)", "Rhesus Macaque", M, ["macaque", "monkey"]))
_add_dsc([3687, 3688], _meta("Dung Beetle (Onthophagus sp.)", "Dung Beetle", INV, ["beetle", "dung beetle"]))
_add_dsc([3704], _meta("Tree branches", "Bare Tree Branches", NATURE, ["nature", "tree"]))
_add_dsc([3732, 3757, 3857, 9784], _meta("Common Tailorbird (Orthotomus sutorius)", "Common Tailorbird", B, ["tailorbird", "orthotomus"]))
_add_dsc([3738, 3742, 3743, 3747], _meta("Common Tailorbird chick (Orthotomus sutorius)", "Tailorbird Chick", B, ["tailorbird", "chick"]))
_add_dsc([3775], _meta("Land snail", "Land Snails", INV, ["snail", "macro"]))
_add_dsc([3784, 3806], _meta("Wandering Glider (Pantala flavescens)", "Dragonfly", INV, ["dragonfly", "pantala"]))
_add_dsc([3807, 8593, 8594, 8600, 8607, 8613], _meta("Shikra (Accipiter badius)", "Shikra", R, ["shikra", "accipiter", "raptor"]))
_add_dsc([3809, 4305, 4991, 5059, 5060, 8988], _meta("Purple Sunbird (Cinnyris asiaticus)", "Purple Sunbird", B, ["sunbird", "cinnyris"]))
_add_dsc([3846], _meta("Spider (Arachnid)", "Spider on Leaf", INV, ["spider", "macro"]))
_add_dsc([3855], _meta("Fulvous Forest Skimmer (Neurothemis fulvia)", "Dragonfly", INV, ["dragonfly", "neurothemis"]))
_add_dsc([4010, 5579, 5580, 5785, 5787, 9111], _meta("Indian Peafowl (Pavo cristatus)", "Indian Peafowl", B, ["peafowl", "peacock"]))
_add_dsc([4018, 4032], _meta("Indian Flying Fox (Pteropus giganteus)", "Indian Flying Fox", M, ["fruit bat", "bat"]))
_add_dsc([4267, 4268], _meta("Rufous Treepie (Dendrocitta vagabunda)", "Rufous Treepie", B, ["treepie", "dendrocitta"]))
_add_dsc([4468], _meta("Potter wasp", "Potter Wasp", INV, ["wasp", "potter wasp"]))
_add_dsc([4876], _meta("Himalayan Bulbul (Pycnonotus leucogenys)", "Himalayan Bulbul", B, ["bulbul", "pycnonotus"]))
_add_dsc([4956], _meta("Common Kestrel (Falco tinnunculus)", "Common Kestrel", R, ["kestrel", "captive"]))
_add_dsc([4968, 4970, 4971], _meta("Himalayan Bluetail (Tarsiger rufilatus)", "Himalayan Bluetail", B, ["bluetail", "flycatcher"]))
_add_dsc([4990], _meta("Moth (Lepidoptera)", "Spotted Moth", INV, ["moth", "macro"]))
_add_dsc([5045, 1203], _meta("Black-winged Stilt (Himantopus himantopus)", "Black-winged Stilt", BW, ["stilt", "wader"]))
_add_dsc([5185], _meta("Caterpillar", "Moth Larva", INV, ["caterpillar", "macro"]))
_add_dsc([5292], _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite", "elanus"]))
_add_dsc([5443, 5458], _meta("Oriental White-eye (Zosterops palpebrosus)", "Oriental White-eye", B, ["white-eye", "zosterops"]))
_add_dsc([5617, 9034, 9040], _meta("Spotted Owlet (Athene brama)", "Spotted Owlet", B, ["owlet", "athene", "owl"]))
_add_dsc([5850, 5848], _meta("Bengal Tiger (Panthera tigris)", "White Tiger", M, ["tiger", "captive"]))
_add_dsc([6014, 6015], _meta("Praying Mantis", "Praying Mantis", INV, ["mantis", "insect"]))
_add_dsc([6105, 6107], _meta("Brown-headed Barbet (Psilopogon zeylanicus)", "Brown-headed Barbet", B, ["barbet", "psilopogon"]))
_add_dsc([7512], _meta("Brahminy Kite (Haliastur indus)", "Brahminy Kite", R, ["kite", "haliastur"]))
_add_dsc([7564, 9213], _meta("Indian Spot-billed Duck (Anas poecilorhyncha)", "Spot-billed Duck", BW, ["duck", "spot-billed"]))
_add_dsc([7580, 7581, 9160], _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Ducks", BW, ["duck", "domestic"]))
_add_dsc([7656, 7853, 7891, 8441], _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant", "phalacrocorax"]))
_add_dsc([7918, 7919], _meta("Emu (Dromaius novaehollandiae)", "Emu", B, ["emu", "captive"]))
_add_dsc([8018, 8023], _meta("Indian Giant Squirrel (Ratufa indica)", "Malabar Giant Squirrel", M, ["squirrel", "ratufa"]))
_add_dsc([8503], _meta("Checkered Keelback (Fowlea piscator)", "Checkered Keelback", REP, ["snake", "keelback", "water snake"]))
_add_dsc([8590], _meta("Plumeria (Frangipani)", "Plumeria Flower", ["nature", "flora"], ["flower", "plumeria"]))
_add_dsc([8620], _meta("Dead fish", "Fish Carcass", ["nature"], ["environment", "documentation"]))
_add_dsc([8660, 8665, 4515, 4534, 9999], _meta("Signature Spider (Argiope sp.)", "Signature Spider", INV, ["spider", "argiope"]))
_add_dsc([8695, 8520], _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital", "deer"]))
_add_dsc([8802, 8803, 8806, 8820], _meta("Cinereous Tit (Parus cinereus)", "Cinereous Tit", B, ["tit", "parus"]))
_add_dsc([8854, 8860], _meta("Indian Water Buffalo (Bubalus bubalis)", "Water Buffalo", M, ["buffalo", "captive"]))
_add_dsc([8855], _meta("Forest sunrise", "Forest Landscape", NATURE, ["landscape", "sunrise"]))
_add_dsc([8875], _meta("Glossy Ibis (Plegadis falcinellus)", "Glossy Ibis", BW, ["ibis", "plegadis"]))
_add_dsc([8929], _meta("Bird at nest box", "Nest Box", B, ["nest", "bird box"]))
_add_dsc([8931], _meta("Vegetation", "Plant Photo", NATURE, ["plant", "nature"]))
_add_dsc([8942], _meta("Red Ixora flower", "Ixora Flower", ["nature", "flora"], ["flower", "ixora"]))
_add_dsc([8950], _meta("Purple Heart (Tradescantia pallida)", "Purple Heart Flower", ["nature", "flora"], ["flower", "tradescantia"]))
_add_dsc([8960], _meta("Grey bird", "Unidentified Grey Bird", B, ["bird"]))
_add_dsc([9090], _meta("Large Grey Babbler (Turdoides malcolmi)", "Large Grey Babbler", B, ["babbler", "turdoides"]))
_add_dsc([9130], _meta("Small bird in nest box", "Nest Box Bird", B, ["nest", "passerine"]))
_add_dsc([9280, 9281, 9282, 8636, 8637, 8638, 8639, 8640], _meta("Domestic Cat (Felis catus)", "Domestic Cat", M, ["cat", "felis"]))
_add_dsc([9583], _meta("Water Lily", "Water Lily Flower", ["nature", "flora"], ["flower", "water lily"]))
_add_dsc([9892], _meta("Little Grebe (Tachybaptus ruficollis)", "Little Grebe", BW, ["grebe", "little grebe"]))
_add_dsc([8625], _meta("Great Egret (Ardea alba)", "Great Egret", BW, ["egret", "ardeidae"]))
_add_dsc([8647], _meta("Great Egret and Glossy Ibis", "Great Egret with Ibis", BW, ["egret", "ibis"]))
_add_dsc([8651], _meta("Dead bird", "Bird Carcass", ["nature"], ["documentation"]))
_add_dsc([1258], _meta("Indian Golden Oriole (Oriolus kundoo)", "Indian Golden Oriole", B, ["oriole", "oriolus"]))
_add_dsc([4203, 4213], _meta("Common Hoopoe (Upupa epops)", "Common Hoopoe", B, ["hoopoe", "upupa"]))
_add_dsc([5280], _meta("Wire-tailed Swallow (Hirundo smithii)", "Wire-tailed Swallow", B, ["swallow", "hirundo"]))
_add_dsc([5657], _meta("Cattle Egret (Bubulcus ibis)", "Cattle Egret", BW, ["egret", "bubulcus"]))
_add_dsc([5876], _meta("Common Mormon (Papilio polytes)", "Common Mormon Butterfly", INV, ["butterfly", "papilio"]))
_add_dsc([38201], _meta("Ashy Prinia (Prinia socialis)", "Ashy Prinia", B, ["prinia", "warbler"]))
_add_dsc([9182, 9289], _meta("Painted Burrowing Frog (Uperodon taprobanicus)", "Painted Burrowing Frog", AMPH, ["frog", "amphibian"]))
_add_dsc([9196, 9202], _meta("Blue Tiger (Tirumala limniace)", "Blue Tiger Butterfly", INV, ["butterfly", "tirumala"]))
_add_dsc([9214], _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant Taking Off", BW, ["cormorant"]))
_add_dsc([9216], _meta("Indian Spot-billed Duck (Anas poecilorhyncha)", "Spot-billed Duck", BW, ["duck"]))
_add_dsc([9247, 9423, 9349], _meta("Common Kingfisher (Alcedo atthis)", "Common Kingfisher", BW, ["kingfisher", "alcedo"]))
_add_dsc([9285], _meta("Crimson Marsh Glider (Trithemis aurora)", "Dragonfly", INV, ["dragonfly", "trithemis"]))
_add_dsc([9295], _meta("Painted Burrowing Frog (Uperodon taprobanicus)", "Painted Burrowing Frog", AMPH, ["frog"]))
_add_dsc([9306], _meta("Freshwater fish", "Fish at Surface", ["wildlife", "aquatic"], ["fish", "freshwater"]))
_add_dsc([9328], _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Ducks", BW, ["duck", "domestic", "muscovy"]))
_add_dsc([9331], _meta("Grey Heron (Ardea cinerea)", "Grey Heron in Foliage", BW, ["heron"]))
_add_dsc([9386], _meta("Little Egret (Egretta garzetta)", "Little Egret on Stump", BW, ["egret"]))
_add_dsc([9407, 9445], _meta("Indian Pond Heron (Ardeola grayii)", "Indian Pond Heron", BW, ["pond heron", "ardeola"]))
_add_dsc([9466], _meta("Little Cormorant (Microcarbo niger)", "Little Cormorant in Tree", BW, ["cormorant"]))
_add_dsc([9491, 9501], _meta("Brahminy Kite (Haliastur indus)", "Brahminy Kite", R, ["kite", "haliastur"]))
_add_dsc([9521], _meta("White-throated Kingfisher (Halcyon smyrnensis)", "White-throated Kingfisher", B, ["kingfisher", "halcyon"]))
_add_dsc([9538, 9549], _meta("Pied Kingfisher (Ceryle rudis)", "Pied Kingfisher", BW, ["kingfisher", "pied kingfisher"]))

# Variant slugs (parentheses, tildes)
def _add_slug(slug, meta):
    MAPPING[slug] = meta

_add_slug("dsc-3709~2", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater with Bulbul", B, ["bee-eater"]))
_add_slug("dsc-4446-(2)", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater", B, ["bee-eater"]))
_add_slug("dsc-3711", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater Pair", B, ["bee-eater"]))
_add_slug("dsc-3712", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eaters", B, ["bee-eater"]))
_add_slug("dsc-3714", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater Flock", B, ["bee-eater"]))
_add_slug("dsc-3773(1)", _meta("Indian Grey Hornbill (Ocyceros birostris)", "Indian Grey Hornbill", B, ["hornbill"]))
_add_slug("dsc-3732(1)", _meta("Common Tailorbird chick (Orthotomus sutorius)", "Tailorbird Chick", B, ["tailorbird", "chick"]))
_add_slug("dsc-3747~2", _meta("Common Tailorbird chick (Orthotomus sutorius)", "Tailorbird Chick", B, ["tailorbird"]))
_add_slug("dsc-3775-1", _meta("Land snail", "Land Snails", INV, ["snail"]))
_add_slug("dsc-4305~2", _meta("Purple Sunbird (Cinnyris asiaticus)", "Purple Sunbird", B, ["sunbird"]))
_add_slug("dsc-4518(1)", _meta("Jumping Spider", "Jumping Spider", INV, ["spider"]))
_add_slug("dsc-4534-(3)", _meta("Orb-weaver Spider", "Orb-weaver Spider", INV, ["spider", "orb-weaver"]))
_add_slug("dsc-4630~2", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater", B, ["bee-eater"]))
_add_slug("dsc-4717-(2)", _meta("Green Bee-eater (Merops orientalis)", "Green Bee-eater", B, ["bee-eater"]))
_add_slug("dsc-4722", _meta("Common Coot (Fulica atra)", "Common Coot", BW, ["coot"]))
_add_slug("dsc-4726-(2)", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet"]))
_add_slug("dsc-4743-(2)", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet"]))
_add_slug("dsc-4759~2", _meta("Little Cormorant (Microcarbo niger)", "Little Cormorant", BW, ["cormorant"]))
_add_slug("dsc-4774-(2)", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet"]))
_add_slug("dsc-4821-(2)", _meta("Common Coot (Fulica atra)", "Common Coot", BW, ["coot"]))
_add_slug("dsc-5045-copy", _meta("Black-winged Stilt (Himantopus himantopus)", "Black-winged Stilt", BW, ["stilt"]))
_add_slug("dsc-5292(1)", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5293", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5293~2", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5294(1)", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5294", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5295", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5295~2", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5296", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5296~2", _meta("Black-winged Kite (Elanus caeruleus)", "Black-winged Kite", R, ["kite"]))
_add_slug("dsc-5458~2", _meta("Oriental White-eye (Zosterops palpebrosus)", "Oriental White-eye", B, ["white-eye"]))
_add_slug("dsc-5460~2", _meta("Oriental White-eye (Zosterops palpebrosus)", "Oriental White-eye", B, ["white-eye"]))
_add_slug("dsc-5621(1)", _meta("Barn Swallow (Hirundo rustica)", "Barn Swallow", B, ["swallow"]))
_add_slug("dsc-5848~2", _meta("Bengal Tiger (Panthera tigris)", "White Tiger", M, ["tiger"]))
_add_slug("dsc-5886~2", _meta("Butterfly", "Butterfly", INV, ["butterfly"]))
_add_slug("dsc-6107~2", _meta("Brown-headed Barbet (Psilopogon zeylanicus)", "Brown-headed Barbet", B, ["barbet"]))
_add_slug("dsc-7512~2", _meta("Brahminy Kite (Haliastur indus)", "Brahminy Kite", R, ["kite"]))
_add_slug("dsc-8396~2", _meta("Common Kingfisher (Alcedo atthis)", "Common Kingfisher", BW, ["kingfisher"]))
_add_slug("dsc-8451~2", _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital"]))
_add_slug("dsc-8451~3", _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital"]))
_add_slug("dsc-8503~2", _meta("Checkered Keelback (Fowlea piscator)", "Checkered Keelback", REP, ["snake"]))
_add_slug("dsc-8503~4", _meta("Checkered Keelback (Fowlea piscator)", "Checkered Keelback", REP, ["snake"]))
_add_slug("dsc-8517~2", _meta("Checkered Keelback (Fowlea piscator)", "Checkered Keelback", REP, ["snake"]))
_add_slug("dsc-8520~2", _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital"]))
_add_slug("dsc-8521~2", _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital"]))
_add_slug("dsc-8660-copy", _meta("Signature Spider (Argiope sp.)", "Signature Spider", INV, ["spider"]))
_add_slug("dsc-8686-copy", _meta("Spotted Deer (Axis axis)", "Chital", M, ["chital"]))
_add_slug("dsc-8631-copy", _meta("Domestic Cat (Felis catus)", "Domestic Cat", M, ["cat"]))
_add_slug("dsc-8987~2", _meta("Indian Robin (Copsychus fulicatus)", "Indian Robin", B, ["indian robin"]))
_add_slug("dsc-9088~2", _meta("Large Grey Babbler (Turdoides malcolmi)", "Large Grey Babbler", B, ["babbler"]))
_add_slug("dsc-9111~2", _meta("Indian Peafowl (Pavo cristatus)", "Indian Peafowl", B, ["peafowl"]))

# IMG / other files (slug = stem.lower().replace(" ", "-").replace("_", "-"))
_add_slug("img-20201110-193427", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201111-110614", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201111-110616", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201111-110622", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201111-110630", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201111-110634", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092648", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092700", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092705", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092706", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092708", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092713", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092715", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092822", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201114-092825", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20201227-195750", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210124-111210", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210313-154235", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210419-205039", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210419-205048", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210420-102128", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img-20210420-102131", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231117173133", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231117173208", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231117173210", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231117173213", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231123194847", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231123194848", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231123194854", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231123194854~2", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231124152952", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231124153000", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231127172612", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231128162152", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("img20231128162154", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog", M, ["dog"]))
_add_slug("screenshot_20201111-113741", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog Puppy", M, ["dog", "puppy"]))
_add_slug("img-1581", _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Duck", BW, ["duck"]))
_add_slug("img-1582", _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Duck", BW, ["duck"]))
_add_slug("img-1583", _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Duck", BW, ["duck"]))
_add_slug("img-1584", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1584-copy", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1585", _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Duck", BW, ["duck"]))
_add_slug("img-1586", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1586-copy", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1587", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1587-copy", _meta("Great Cormorant (Phalacrocorax carbo)", "Great Cormorant", BW, ["cormorant"]))
_add_slug("img-1588-copy", _meta("Ictinogomphus clubtail dragonfly", "Clubtail Dragonfly", INV, ["dragonfly"]))
_add_slug("img-1590", _meta("Buff-striped Keelback (Amphiesma stolatum)", "Buff-striped Keelback", REP, ["snake", "keelback"]))
_add_slug("img-1591", _meta("Buff-striped Keelback (Amphiesma stolatum)", "Buff-striped Keelback", REP, ["snake"]))
_add_slug("img-1591-copy", _meta("Buff-striped Keelback (Amphiesma stolatum)", "Buff-striped Keelback", REP, ["snake"]))
_add_slug("img-1592", _meta("Domestic Chicken (Gallus gallus domesticus)", "Domestic Chickens", B, ["chicken"]))
_add_slug("img-1594", _meta("Domestic Chicken (Gallus gallus domesticus)", "Domestic Chickens", B, ["chicken"]))
_add_slug("img-1596", _meta("Domestic Duck (Anas platyrhynchos domesticus)", "Domestic Duck", BW, ["duck"]))
_add_slug("img-20171019-081923721", _meta("Land snail", "Land Snail", INV, ["snail"]))
_add_slug("img_20191122-030947-133", _meta("House Crow (Corvus splendens)", "House Crow", B, ["crow"]))
_add_slug("img_20191124-135048", _meta("Taxidermied Bengal Tiger", "Bengal Tiger Taxidermy", M, ["tiger"]))
_add_slug("img_20191125-104416", _meta("Hanuman Langur (Semnopithecus entellus)", "Hanuman Langur", M, ["langur", "monkey"]))
_add_slug("img_20191227-152152", _meta("Asiatic Lion (Panthera leo persica)", "Asiatic Lion", M, ["lion", "captive"]))
_add_slug("img_20191227-152154", _meta("Asiatic Lion (Panthera leo persica)", "Asiatic Lion", M, ["lion", "captive"]))
_add_slug("img_20200503-181104-672", _meta("Cabbage White (Pieris brassicae)", "Cabbage White Butterfly", INV, ["butterfly"]))
_add_slug("img_20201013-080317", _meta("Cotton Stainer Bug (Dysdercus cingulatus)", "Cotton Stainer", INV, ["bug", "cotton stainer"]))
_add_slug("img_20210619-200636", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar", "captive"]))
_add_slug("img_20210619-200657", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210619-200703", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210619-200706", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210619-200714", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210619-200759", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210619-200801", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20211024-195236", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20211024-195238", _meta("Budgerigar (Melopsittacus undulatus)", "Budgerigar", B, ["budgerigar"]))
_add_slug("img_20210719-060512", _meta("Domestic Rabbit (Oryctolagus cuniculus domesticus)", "Domestic Rabbits", M, ["rabbit", "captive"]))
_add_slug("img_20210816-101248", _meta("Garden/terrace", "Garden View", NATURE, ["garden", "nature"]))
_add_slug("img_20210925-162025", _meta("Rock Pigeon (Columba livia)", "Rock Pigeon Chicks", B, ["pigeon", "chicks"]))
_add_slug("img_20210925-162029", _meta("Rock Pigeon (Columba livia)", "Rock Pigeon Chicks", B, ["pigeon"]))
_add_slug("img_20210925-171941", _meta("Lime Swallowtail caterpillar (Papilio demoleus)", "Lime Swallowtail Caterpillar", INV, ["caterpillar", "butterfly"]))
_add_slug("img_20210925-171951", _meta("Lime Swallowtail caterpillar (Papilio demoleus)", "Lime Swallowtail Caterpillar", INV, ["caterpillar"]))
_add_slug("img_20220224-113458", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog Puppy", M, ["dog", "puppy"]))
_add_slug("img_20220224-113518_bokeh", _meta("Indian Pariah Dog (Canis lupus familiaris)", "Street Dog Puppy", M, ["dog"]))
_add_slug("img20231028094041", _meta("Hawkmoth caterpillar", "Hawkmoth Caterpillar", INV, ["caterpillar", "hawkmoth"]))
_add_slug("img20231107204848", _meta("Atlas Moth (Attacus atlas)", "Silk Moth", INV, ["moth", "atlas"]))
_add_slug("img20231107204850", _meta("Atlas Moth (Attacus atlas)", "Silk Moth", INV, ["moth"]))
_add_slug("img20231202093905", _meta("Siberian Husky (Canis lupus familiaris)", "Siberian Husky", M, ["husky", "dog", "pet"]))
_add_slug("img20231202093908", _meta("Siberian Husky (Canis lupus familiaris)", "Siberian Husky", M, ["husky"]))
_add_slug("img20231202093911", _meta("Siberian Husky (Canis lupus familiaris)", "Siberian Husky", M, ["husky"]))
_add_slug("img20231202093912", _meta("Siberian Husky (Canis lupus familiaris)", "Siberian Husky", M, ["husky"]))
_add_slug("img20231202093913", _meta("Siberian Husky (Canis lupus familiaris)", "Siberian Husky", M, ["husky"]))
_add_slug("img20231215100632", _meta("Oriental Garden Lizard (Calotes versicolor)", "Oriental Garden Lizard", REP, ["lizard"]))
_add_slug("img20231215100635", _meta("Oriental Garden Lizard (Calotes versicolor)", "Oriental Garden Lizard", REP, ["lizard"]))
_add_slug("img20231215100635~2", _meta("Oriental Garden Lizard (Calotes versicolor)", "Oriental Garden Lizard", REP, ["lizard"]))
_add_slug("img20231215124005", _meta("Domestic Cat (Felis catus)", "Domestic Cat", M, ["cat"]))
_add_slug("img20231215124436", _meta("Domestic Cat (Felis catus)", "Domestic Cat", M, ["cat"]))
_add_slug("img20231215124440", _meta("Domestic Cat (Felis catus)", "Domestic Cat", M, ["cat"]))
_add_slug("img20240703091242_01", _meta("Common Kingfisher (Alcedo atthis)", "Common Kingfisher", BW, ["kingfisher"]))
_add_slug("img_20200503-154559-903", _meta("House Sparrow (Passer domesticus)", "House Sparrow", B, ["sparrow"]))
_add_slug("img_20191122-030713-963", _meta("Black Kite (Milvus migrans)", "Black Kite", R, ["kite"]))
_add_slug("img_20191122-031146-947", _meta("Indian Palm Squirrel (Funambulus palmarum)", "Indian Palm Squirrel", M, ["squirrel"]))
_add_slug("img_20191122-031311-089", _meta("Rhesus Macaque (Macaca mulatta)", "Rhesus Macaque", M, ["macaque"]))
_add_slug("img_20210313-151205", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet", "captive"]))
_add_slug("img_20210619-091439", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet"]))
_add_slug("img_20210925-180347", _meta("Rose-ringed Parakeet (Psittacula krameri)", "Rose-ringed Parakeet", B, ["parakeet"]))
_add_slug("img_20210801-104052", _meta("Asian Openbill Stork (Anastomus oscitans)", "Asian Openbill", BW, ["stork"]))
_add_slug("img_20210801-104154", _meta("Asian Openbill Stork (Anastomus oscitans)", "Asian Openbill", BW, ["stork"]))
_add_slug("img_20210801-104207", _meta("Asian Openbill Stork (Anastomus oscitans)", "Asian Openbill", BW, ["stork"]))
_add_slug("img_20210102-162114", _meta("Rock Pigeon (Columba livia)", "Rock Pigeon Flock", B, ["pigeon"]))
_add_slug("img_20220120-200722", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-200735-copy", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-200742", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-200759", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-200843", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-200849", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20220120-223428", _meta("Praying Mantis", "Praying Mantis", INV, ["mantis"]))
_add_slug("img_20230526-06440309", _meta("Brown-headed Barbet (Psilopogon zeylanicus)", "Brown-headed Barbet", B, ["barbet"]))
_add_slug("img_20210722-090601", _meta("Land Snail", "Land Snail", INV, ["snail"]))
_add_slug("dscf1960", _meta("Indian Spot-billed Duck (Anas poecilorhyncha)", "Spot-billed Duck", BW, ["duck"]))
_add_slug("file0148-edit", _meta("Indian Grey Hornbill (Ocyceros birostris)", "Indian Grey Hornbill", B, ["hornbill"]))
_add_slug("inshot_20230730-220039893", _meta("Indian Peafowl (Pavo cristatus)", "Indian Peafowl Display", B, ["peafowl"]))
_add_slug("inshot_20240212-102406327", _meta("Checkered Keelback (Fowlea piscator)", "Checkered Keelback with Fish", REP, ["snake", "keelback"]))
_add_slug("dji_fly-536070330-231640-157-1695998873820-photo", _meta("Indian Peafowl (Pavo cristatus)", "Peafowl on Tower", B, ["peafowl", "aerial"]))
_add_slug("a-lazy-hawk-beautifying-himself-(1)-moment", _meta("Shikra (Accipiter badius)", "Shikra Preening", R, ["shikra"]))
_add_slug("a-lazy-hawk-beautifying-himself-(2)-moment", _meta("Shikra (Accipiter badius)", "Shikra Preening", R, ["shikra"]))
_add_slug("dsc-4254", _meta("Cotton Stainer Bug (Dysdercus cingulatus)", "Cotton Stainer", INV, ["bug"]))
